config/routes.rb
Rails.application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  post '/users/:user_id/articles/:id' => 'articles#create', :as => "new_article"
  post '/users/:user_id/articles/:id/edit' => 'articles#update',:as => 'update_article'

root :to => "welcome#index"

resources :sessions
resources :users do
  resources :articles
end

  get 'welcome/index'

  
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base  
  has_many :articles, dependent: :destroy
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

def index
  @user = User.find(session[:user_id])
  @article = @user.articles
end
  
def show
  @user = User.find(session[:user_id])
  @article = @user.articles.find(params[:id])
end

def edit
  @user = User.find(session[:user_id])
  @article = @user.articles.find(params[:id])
end

def new
  @article = Article.new
end
 
def create
  user = User.find(session[:user_id])   
  @article = user.articles.create(article_params)
 
  if @article.save
    redirect_to user_article_path(:user_id => user.id,:id => @article.id)
  else
    render 'new'
  end 
end

def update
  @user = User.find(session[:user_id])   
  @article = @user.articles.find(params[:id])

  if @article.update(article_params)
    redirect_to user_article_path(:user_id => @user.id,:id => @article.id)
  else
    render 'edit'
  end
end

def destroy
  @user = User.find(session[:user_id])   
  @article = @user.articles.find(params[:id])
  
  @article.destroy
  redirect_to user_articles_path
end

private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to  new_user_article_path(session[:user_id])
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end
def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
   def new
     @user = User.new 
   end
   def create
     @user = User.new(users_params)
     if @user.save
      session[:user_id] = @user.id
      redirect_to  new_user_article_path(session[:user_id])
     else
     render "new"
   end
 end
 def users_params
  params.require(:user).permit(:email, :password, :password_confirmation)
end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@article = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for :article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', user_articles_path %>

app/views/articles/index.html.erb
<%= link_to 'Back', new_user_article_path %>
<table>
  <tr>
    <th align="left">Title</th>
    <th align="left">Text</th>
  </tr>
 
 <% @article.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Edit', edit_user_article_path(:id => article.id) %></td>
      <td><%= link_to 'Delete', user_article_path(:id => article.id), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%= render 'form' %>
<%= link_to 'Show All Articles', user_articles_path %>
<%= link_to 'Back', welcome_index_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<%= link_to 'Edit', edit_user_article_path %> |
<%= link_to 'Back', user_articles_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
  <% end %>
</div>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
  <p><%= link_to 'Log in ', log_in_path %></p>
  <p><%= link_to "Go to Main Page", welcome_index_path %></p>
<% end %>

app/views/welcome/index.html.erb
<% if current_user %>
  <%= link_to "My Account", new_user_article_path(:user_id => session[:user_id]) %>
  <h1> List of all the Articles </h1>
  <table>
  <tr>
    <th align="left">Title</th>
    <th align="left">Text</th>
  </tr>
  <% @article.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td ><%= article.text %></td>
      <% if article.user_id == session[:user_id] %>
      <td><%= link_to 'Edit', edit_user_article_path(:user_id => session[:user_id], :id => article.id) %></td>
      <td><%= link_to 'Delete', user_article_path(:user_id => session[:user_id],:id => article.id), method: :delete %></td>
      <% else %>
      <% end %>
    </tr>
  
  <% end %>
</table>
<% else %>
  <%= link_to "Login", new_session_path %>
  <h1> List of all the Articles </h1>
<table>
  <tr>
    <th align="left">Title</th>
    <th align="left">Text</th>
  </tr>
  <% @article.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </tr>
  
  <% end %>
</table>
<% end %>